version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mailer:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/mailer
    command: >
      sh -c "
        alembic upgrade head &&
        celery -A tasks.send_email_batch worker --loglevel=info
      "